name: Build and Deploy Wiki

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get list of Markdown files
        run: |
          FILES=$(find docs -name "*.md" -type f | tr '\n' ',' | sed 's/,$//')
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1.1.0
        with:
          path: ${{ env.FILES }}
          outputpath: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
